//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flykits.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Rod { get; set; }
        public string Line { get; set; }
        public int Rating { get; set; }
        public string img { get; set; }
    }
}
